server:
    adminMinThreads: 1
    adminMaxThreads: 10
    adminContextPath: ${ADMIN_CONTEXT_PATH:- /}
    applicationContextPath: /
    applicationConnectors:
        - type: http
          port: 8099
        - type: https
          port: 8445
          keyStorePath: /home/jc064522/dev/gchq/certs/certs3/keystore.jks
          keyStorePassword: changeit
          trustStorePath: /home/jc064522/.sdkman/candidates/java/current/jre/lib/security/cacerts
          #trustStorePassword: stroompassword1
          #validateCerts: true
          keyStoreType: JKS
          supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2]
    adminConnectors:
        - type: http
          port: 8100

database:
    driverClass: com.mysql.jdbc.Driver
    user: ${DB_USER:- stroomuser}
    password: ${DB_PASSWORD:- stroompassword1}
    url: ${DB_URL:- jdbc:mysql://localhost:3307/stroom?useUnicode=yes&characterEncoding=UTF-8}

    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
        #set to false for compatibility with stroom's legacy hibernate 4 configuration and schema
        hibernate.id.new_generator_mappings: false
        hibernate.show_sql: false

logging:
  level: ERROR
  loggers:
    stroom: DEBUG
    io.dropwizard: DEBUG
    org.eclipse.jetty: DEBUG
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

jooq:
  dialect: MYSQL
  logExecutedSql: yes
  renderSchema: yes
  renderNameStyle: QUOTED
  renderKeywordStyle: LOWER
  renderFormatted: no
  paramType: INDEXED
  statementType: PREPARED_STATEMENT
  executeLogging: no
  executeWithOptimisticLocking: no
  attachRecords: yes
  updatablePrimaryKeys: no

jwsExpirationTimeInMinutesInTheFuture: 5
jwsIssuer: stroom
jwsSecret: ${JWS_SECRET:- CHANGE_ME}
certificateDnPattern: CN=[^ ]+ [^ ]+ \(?([a-zA-Z0-9]+)\)?
loginUrl: http://localhost/login
stroomUrl: http://localhost/stroom