server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8081

database:
    driverClass: com.mysql.jdbc.Driver
    user: ${STATS_DB_USER:- stroomuser}
    password: ${STATS_DB_PASSWORD:- stroompassword1}
    url: ${STATS_DB_URL:- jdbc:mysql://localhost:3307/stroom?useUnicode=yes&characterEncoding=UTF-8}

    properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
        #set to false for compatibility with stroom's legacy hibernate 4 configuration and schema
        hibernate.id.new_generator_mappings: false
        hibernate.show_sql: false

logging:
  level: ERROR
  loggers:
    stroom: DEBUG
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC

jooq:
  dialect: MYSQL
  logExecutedSql: yes
  renderSchema: yes
  renderNameStyle: QUOTED
  renderKeywordStyle: LOWER
  renderFormatted: no
  paramType: INDEXED
  statementType: PREPARED_STATEMENT
  executeLogging: no
  executeWithOptimisticLocking: no
  attachRecords: yes
  updatablePrimaryKeys: no

jwsExpirationTimeInMinutesInTheFuture: 5
jwsIssuer: stroom
jwsSecret: CHANGE_ME